### PR TITLE
Component tweaks

### PR DESCRIPTION
**Pull request by mattias-p**
- Improved floor alignment
- Disallow obstacle cheating
- Optimize dev room template, just for kicks
- Add proper hole borders

### CODE REVIEW

**Comment by mattias-p** [comment]
There's another glove obstacle where you can hookshot over a hole. I suggest I re-review the glove obstacles and include more commits in this pull request.

**Comment by mattias-p** [comment]
There's also a glove obstacle with a missing wall border.

**Comment by mattias-p** [comment]
Fixed the above issues.

**Comment by sandstrand** [comment]
Remove room1 backdrop tiles from enemy_boss_000777_3 and we are set.

**Pull request merged**
